// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5_eMpG1Zaa-rODSsEBTCU1M1nok3Qwgk',
    appId: '1:976091888225:web:87ee42bb0611c3bd8ec820',
    messagingSenderId: '976091888225',
    projectId: 'test1-472911',
    authDomain: 'test1-472911.firebaseapp.com',
    storageBucket: 'test1-472911.firebasestorage.app',
    measurementId: 'G-M6LX1QT63Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALS7hhFOvHS0F3IbCppMQ67BzWtPCLl9g',
    appId: '1:976091888225:android:2447f835647383938ec820',
    messagingSenderId: '976091888225',
    projectId: 'test1-472911',
    storageBucket: 'test1-472911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVHhSziaWGB1Y7IAmKxlK2elJ1Ad-UKaA',
    appId: '1:976091888225:ios:589b6ad1e13cc6768ec820',
    messagingSenderId: '976091888225',
    projectId: 'test1-472911',
    storageBucket: 'test1-472911.firebasestorage.app',
    iosBundleId: 'com.example.memoGift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVHhSziaWGB1Y7IAmKxlK2elJ1Ad-UKaA',
    appId: '1:976091888225:ios:589b6ad1e13cc6768ec820',
    messagingSenderId: '976091888225',
    projectId: 'test1-472911',
    storageBucket: 'test1-472911.firebasestorage.app',
    iosBundleId: 'com.example.memoGift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5_eMpG1Zaa-rODSsEBTCU1M1nok3Qwgk',
    appId: '1:976091888225:web:aad8d63950e59d538ec820',
    messagingSenderId: '976091888225',
    projectId: 'test1-472911',
    authDomain: 'test1-472911.firebaseapp.com',
    storageBucket: 'test1-472911.firebasestorage.app',
    measurementId: 'G-BGCMQ2R1QE',
  );
}
